Repository acm-ucr/nsu-website, pull requests merged in 2025-04, with the labels that each got.

#27 Made Join Us Button
  src/components/Home/JoinUsButton.tsx
  src/components/Home/Offer.tsx
Labels: Ready for review

#35 i-vvnn Double Cards for Additional Information Implementation
  package-lock.json
  src/components/Home/AdditionalInfo.tsx
Labels: address comments, home

#28 Add offers section
  src/components/Home/Offer.tsx
Labels: address comments

#38 BestinMW About Section One
  src/components/about/AboutSection1.tsx
Labels: Ready for review

#34 Rishik pulipaka/footer
  package-lock.json
  package.json
  src/app/layout.tsx
  src/components/Footer.tsx
Labels: address comments

#41 About section 2 completed
  package-lock.json
  src/components/about/AboutSection2.tsx
Labels: Ready for review

#42 Pranay5432/create board card
  public/assets/nsunamebarflag.svg
  src/app/board/page.tsx
  src/components/board/BoardCard.tsx
Labels: address comments

#43 added navbar
  src/app/layout.tsx
  src/app/page.tsx
  src/components/NavBar.tsx
Labels: Ready for review

#48 Cade jordan/welcome section
  src/components/Home/Welcome.tsx
Labels: Ready for review

#52 fixed line issue
  src/components/about/AboutSection2.tsx
Labels: Ready for review

#55 Howardwheeler/board
  package-lock.json
  package.json
  src/app/board/page.tsx
  src/components/board/BoardCard.tsx
  src/components/board/BoardGrid.tsx
  src/data/Board.ts
Labels: Ready for review

#47 Landing
  public/assets/lanterns.webp
  src/components/Home/Landing.tsx
Labels: Ready for review

#53 Header component
  src/app/about/page.tsx
  src/app/board/page.tsx
  src/app/events/page.tsx
  src/app/photos/page.tsx
  src/components/Header.tsx
Labels: Ready for review
