Repository acm-ucr/nsu-website, pull requests merged in 2025-05, with the labels that each got.

#54 Created gallery grid
  public/photos/CIMG1842.webp
  public/photos/CIMG1845.webp
  public/photos/CIMG1854.webp
  public/photos/CIMG1869.webp
  public/photos/CIMG1887.webp
  public/photos/CIMG1897.webp
  public/photos/CIMG1972.webp
  public/photos/CIMG1974.webp
  public/photos/CIMG1980.webp
  public/photos/CIMG1982.webp
  public/photos/CIMG1988.webp
  public/photos/CIMG2022.webp
  public/photos/CIMG2144.webp
  public/photos/CIMG2169.webp
  public/photos/CIMG2174.webp
  public/photos/CIMG2185.webp
  public/photos/CIMG2281.webp
  public/photos/DSC00045.webp
  public/photos/DSC00060.webp
  public/photos/DSC00082.webp
  public/photos/DSC00092.webp
  public/photos/DSC00114.webp
  public/photos/DSC00894.webp
  public/photos/DSC00912.webp
  public/photos/DSC00916.webp
  public/photos/DSC00942.webp
  public/photos/DSC00967.webp
  public/photos/DSC00987.webp
  public/photos/DSC01199.webp
  public/photos/DSC01783.webp
  public/photos/DSC01814.webp
  public/photos/IMG_1008.webp
  public/photos/IMG_1025.webp
  public/photos/IMG_6175.webp
  public/photos/IMG_6328.webp
  public/photos/IMG_6339.webp
  public/photos/IMG_6343.webp
  public/photos/IMG_7395.webp
  public/photos/fam_wars.webp
  public/photos/reveal.webp
  src/components/photos/Gallery2.tsx
Labels: Ready to Merge

#64 about socials
  src/components/about/Socials.tsx
  src/data/Socials.tsx
Labels: Ready for review

#57 Pranay5432/footerimage
  public/assets/footer.svg
  src/components/Footer.tsx
Labels: address comments

#71 PaggMan/ResponsifyLanding
  src/components/Home/Landing.tsx
Labels: Ready for review

#70 mobile navbar
  src/app/about/page.tsx
  src/app/board/page.tsx
  src/app/events/page.tsx
  src/app/gallery/page.tsx
  src/components/NavBar.tsx
  src/components/about/TitleSection.tsx
  src/components/board/TitleSection.tsx
  src/components/events/TitleSection.tsx
  src/components/gallery/Gallery1.tsx
  src/components/gallery/Gallery2.tsx
  src/components/photos/TitleSection.tsx
Labels: Ready for review

#68 Responsified Welcome Component
  src/components/Home/Welcome.tsx
Labels: Ready for review

#69 responsified gallery
  src/components/gallery/Gallery2.tsx
Labels: Ready for review

#73 Responsify Additional Information Component
  src/components/Home/AdditionalInfo.tsx
Labels: mobile responsiveness, Ready for review

#83 Animated gallery
  package-lock.json
  package.json
  src/components/gallery/Gallery2.tsx
Labels: Ready for review

#89 made about page responsive
  src/components/about/AboutSection1.tsx
  src/components/about/AboutSection2.tsx
Labels: Ready for review

#92 board motion
  src/components/board/BoardGrid.tsx
Labels: Ready for review

#85 Responsified Header
  src/components/Header.tsx
Labels: Ready for review

#93 Fixed sizing of social icons and animated
  src/components/about/Socials.tsx
Labels: Ready for review
